### ISSUE TITLE
Support multiple cursors

### ISSUE THREAD

**Issue by ackvf** [SuperV1234/vscode-expand-selection-to-scope#3]
Add support for multiple cursors. _(Great with transpose.)_

**Comment by vittorioromeo** [comment]
Done! Let me know if this works for you.

Relevant changes [here](https://github.com/SuperV1234/vscode-expand-selection-to-scope/commit/5e53f28f32944847024b55c29732245007aabe7e#diff-45327f86d4438556066de133327f4ca2).

![gif](https://github.com/SuperV1234/vscode-expand-selection-to-scope/raw/master/example_multicursor.gif)

**Comment by ackvf** [comment]
Seems to work like a charm, thanks!
