### ISSUE TITLE
expand string without enclosing quotes first

### ISSUE THREAD

**Issue by mderazon** [SuperV1234/vscode-expand-selection-to-scope#6]
I think it would be useful to first expand to exclude the surrounding quotes and only next step to include the quotes

This:
![](https://dl.dropboxusercontent.com/s/bbrxhukqemcatxo/14FB0500-2C8F-431D-888F-18216514FCE4-3373-0000A67417265F4A.gif?dl=0)

Instead of this:
![](https://dl.dropboxusercontent.com/s/e698gpkkv0j9pud/3BDC45D4-E709-42CA-83D1-6012B8167DC1-3373-0000A688AE57AA84.gif?dl=0)

**Comment by vittorioromeo** [comment]
Just for clarification: the current version of the extension doesn't match neither `"` nor `'`. Are you using a different extension in your second gif?

**Comment by mderazon** [comment]
🤔 

I don't know where it's coming from then... I don't have any other extension that handles this.
Anyway, I guess it's not relevant here then...
