### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by n2lose** [SuperV1234/vscode-expand-selection-to-scope#7]
I can't found any instruction how to usage it. 
In Sublimetext, I often use keyboard Ctrl+Shift+A. 
Can you make it instead of use command?

**Comment by vittorioromeo** [comment]
You need to add a keybinding for the `expand-selection-to-scope.expand` command. Alternatively you can press Ctrl+Shift+P and select the "Expand selection to scope" command. Let me know if that helps.

**Comment by n2lose** [comment]
Thanks!
